### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Magniswerfer** [Magniswerfer/tripleclickdb-node#1]
- [x] generate table from all games in index.js
- [x] have one cell be most recent
- [x] make most recently mentioned list of games in index.js
- [x] figure out how to get data from igdb
- [x] migrate css (and functionality lol) from [static site](https://tripleclickdb.com/)

**Comment by Magniswerfer** [comment]
- [ ] sort incoming games by date, so that is how they appear in table
- [ ] figure out how to sort games in recent games list (seems to be dependent on when they load?)
- [ ] make page for each episode
- [ ] include cover art on game page
- [ ] figure out what to do with bonus episodes!

**Comment by Magniswerfer** [comment]
> * [ ]  sort incoming games by date, so that is how they appear in table
> * [ ]  figure out how to sort games in recent games list (seems to be dependent on when they load?)
> * [ ]  make page for each episode
> * [ ]  include cover art on game page
> * [ ]  figure out what to do with bonus episodes!

[You could simply create two columns in Ticket, OwnedByUserId and OwnedByGroupId, and have nullable Foreign Keys to each table.](https://stackoverflow.com/questions/7844460/foreign-key-to-multiple-tables)
